name: Run build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Make a build
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches
      - name: Deploy
        run: |
          echo "Deploying to the deploy branch......"
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"

          # Fetch all branches
          git fetch origin

          # Checkout the deploy branch
          git checkout -b deploy origin/deploy

          # Get the latest changes from main branch
                    git fetch origin master:master


          # Reset the deploy branch to main (alternative to rebase)
          git rebase master

          # Add built files (adjust the path as needed)
          git add dist/ -f  # or whatever your build output directory is
          git commit -m "Deploy latest changes"

          # Push to deploy branch
          git push origin deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_SECRET }}
